testing the args instead of using calledWith
to see the diff instead of false vs true

before

AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

after

 {
         "error": "Bad Request"
      -  "message": "bad error"
      +  "message": "Error: bad error"
         "statusCode": 400
       }